-- ============================================================================
-- Flashcard deck file — format version 1
--
-- One SQLite file = one deck. The same schema is used on every client and on
-- the server. Tables without a leading underscore are the user's data and are
-- meant to be readable with any SQLite tool. Tables with a leading underscore
-- are sync machinery.
--
-- Conventions
--   IDs         TEXT UUIDs. Entities: UUIDv7, generated by the originating
--               client. Cards: UUIDv5 derived from (fact_id, template_id,
--               ordinal) so every replica computes the same ID.
--   Timestamps  TEXT, ISO 8601 UTC ("2026-09-24T10:53:00.000Z").
--   HLC         TEXT "<wall_ms:13 digits>-<counter:5 digits>-<client_id>".
--               Zero-padded, so plain string comparison = HLC order.
--   Deletes     Tombstones (deleted = 1). Delete wins: any later event that
--               targets a deleted entity is ignored.
--   Foreign keys are declared for documentation; enforcement is off because
--               media bytes and some references can arrive out of order.
-- ============================================================================

PRAGMA user_version = 1;


-- ----------------------------------------------------------------------------
-- Self-description, for readers of this file decades from now.
-- Rows: format, format_version, description, spec_url.
-- ----------------------------------------------------------------------------
CREATE TABLE _about (
  key    TEXT PRIMARY KEY,
  value  TEXT NOT NULL
);


-- ----------------------------------------------------------------------------
-- The deck. Exactly one row.
-- ----------------------------------------------------------------------------
CREATE TABLE deck (
  id           TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  description  TEXT NOT NULL DEFAULT '',
  settings     TEXT NOT NULL DEFAULT '{}',  -- JSON: new_per_day, scheduler, ...
  created_at   TEXT NOT NULL
);


-- ----------------------------------------------------------------------------
-- Fact types: user-defined kinds of facts ("Country", "Vocab", "Cloze").
-- Each live fact type owns one table named table_name (see fact_country below).
-- ----------------------------------------------------------------------------
CREATE TABLE fact_types (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,              -- display name: 'Country'
  table_name  TEXT NOT NULL,              -- SQL identifier: 'fact_country'
  css         TEXT NOT NULL DEFAULT '',   -- styling applied to its cards
  created_at  TEXT NOT NULL,
  deleted     INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX fact_types_live_table ON fact_types(table_name) WHERE deleted = 0;


-- ----------------------------------------------------------------------------
-- Fields: the user-defined columns of a fact type.
-- Events reference fields by id; column_name tracks the current SQL column.
-- ----------------------------------------------------------------------------
CREATE TABLE fields (
  id            TEXT PRIMARY KEY,
  fact_type_id  TEXT NOT NULL REFERENCES fact_types(id),
  name          TEXT NOT NULL,            -- display name: 'Largest City'
  column_name   TEXT NOT NULL,            -- SQL identifier: 'largest_city'
  data_type     TEXT NOT NULL
                CHECK (data_type IN ('text', 'rich_text', 'number', 'image', 'audio')),
  position      TEXT NOT NULL,            -- fractional index; sort ascending
  deleted       INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX fields_live_column ON fields(fact_type_id, column_name) WHERE deleted = 0;


-- ----------------------------------------------------------------------------
-- Templates: how a fact type renders into cards.
--   generation = 'one'        one card per fact
--   generation = 'per_cloze'  one card per distinct {{cN::...}} in the fact
-- front/back use {{Field Name}} placeholders; renaming a field rewrites them.
-- ----------------------------------------------------------------------------
CREATE TABLE templates (
  id            TEXT PRIMARY KEY,
  fact_type_id  TEXT NOT NULL REFERENCES fact_types(id),
  name          TEXT NOT NULL,            -- 'Forward', 'Reverse', 'Cloze'
  generation    TEXT NOT NULL CHECK (generation IN ('one', 'per_cloze')),
  front         TEXT NOT NULL,            -- 'What is the capital of {{Name}}?'
  back          TEXT NOT NULL,            -- '{{Capital}}'
  position      TEXT NOT NULL,
  deleted       INTEGER NOT NULL DEFAULT 0
);


-- ----------------------------------------------------------------------------
-- Fact registry: one row per fact ever created, including tombstones.
-- The fact's values live in its type's table.
-- ----------------------------------------------------------------------------
CREATE TABLE facts (
  id            TEXT PRIMARY KEY,
  fact_type_id  TEXT NOT NULL REFERENCES fact_types(id),
  created_at    TEXT NOT NULL,
  deleted       INTEGER NOT NULL DEFAULT 0
);


-- ----------------------------------------------------------------------------
-- EXAMPLE of a per-fact-type table, created by events, not by this script.
-- Holds live facts only: deleting a fact removes its row here and leaves the
-- tombstone in `facts`. Media fields hold a hash into `media`.
-- ----------------------------------------------------------------------------
-- CREATE TABLE fact_country (
--   id            TEXT PRIMARY KEY REFERENCES facts(id),
--   name          TEXT,
--   capital       TEXT,
--   largest_city  TEXT,
--   flag          TEXT,   -- media hash (image)
--   map           TEXT    -- media hash (image)
-- );


-- ----------------------------------------------------------------------------
-- Cards: derived from (fact, template, ordinal). Never created by an event
-- directly; every replica generates them identically when facts or templates
-- change. A removed cloze that comes back gets the same id, so its review
-- history returns with it.
-- ----------------------------------------------------------------------------
CREATE TABLE cards (
  id           TEXT PRIMARY KEY,          -- UUIDv5(fact_id, template_id, ordinal)
  fact_id      TEXT NOT NULL REFERENCES facts(id),
  template_id  TEXT NOT NULL REFERENCES templates(id),
  ordinal      INTEGER NOT NULL DEFAULT 0,  -- cloze number; 0 for 'one'
  suspended    INTEGER NOT NULL DEFAULT 0,
  deleted      INTEGER NOT NULL DEFAULT 0,
  UNIQUE (fact_id, template_id, ordinal)
);


-- ----------------------------------------------------------------------------
-- Reviews: append-only study history. The source of truth for scheduling.
--   kind = 'review'  a graded answer (grade 1 again, 2 hard, 3 good, 4 easy)
--   kind = 'reset'   forget progress; replay starts after the latest reset
-- ----------------------------------------------------------------------------
CREATE TABLE reviews (
  id           TEXT PRIMARY KEY,          -- UUIDv7, client-generated
  card_id      TEXT NOT NULL REFERENCES cards(id),
  user_id      TEXT NOT NULL,
  kind         TEXT NOT NULL DEFAULT 'review' CHECK (kind IN ('review', 'reset')),
  grade        INTEGER CHECK (grade BETWEEN 1 AND 4),
  reviewed_at  TEXT NOT NULL,             -- client wall clock
  duration_ms  INTEGER,
  voided       INTEGER NOT NULL DEFAULT 0,  -- undo
  CHECK (kind = 'reset' OR grade IS NOT NULL)
);
CREATE INDEX reviews_by_card ON reviews(card_id, user_id, reviewed_at, id);


-- ----------------------------------------------------------------------------
-- Card state: DERIVED CACHE. Rebuild at any time by replaying a card's
-- non-voided reviews in (reviewed_at, id) order. No row = new card.
-- ----------------------------------------------------------------------------
CREATE TABLE card_state (
  card_id      TEXT NOT NULL REFERENCES cards(id),
  user_id      TEXT NOT NULL,
  state        TEXT NOT NULL CHECK (state IN ('new', 'learning', 'review', 'relearning')),
  due_at       TEXT,
  reps         INTEGER NOT NULL DEFAULT 0,
  lapses       INTEGER NOT NULL DEFAULT 0,
  last_review  TEXT,
  scheduler    TEXT NOT NULL,             -- e.g. 'fsrs-5'
  params       TEXT NOT NULL DEFAULT '{}',  -- scheduler-specific JSON
  PRIMARY KEY (user_id, card_id)
);
CREATE INDEX card_state_due ON card_state(user_id, due_at);


-- ----------------------------------------------------------------------------
-- Media: content-addressed blobs (images, audio) stored inside the deck file.
-- data is NULL until the bytes have synced (they travel out of band).
-- ----------------------------------------------------------------------------
CREATE TABLE media (
  hash        TEXT PRIMARY KEY,           -- sha256 hex of data
  mime_type   TEXT NOT NULL,
  data        BLOB,
  created_at  TEXT NOT NULL
);


-- ============================================================================
-- Sync machinery
-- ============================================================================

-- Event log: source of truth for everything above.
-- On clients, rows with seq IS NULL are the outbox (pending push).
CREATE TABLE _events (
  id          TEXT PRIMARY KEY,           -- op id, UUIDv7; dedupe key
  seq         INTEGER UNIQUE,             -- server-assigned order; NULL = pending
  hlc         TEXT NOT NULL,
  client_id   TEXT NOT NULL,
  user_id     TEXT NOT NULL,
  type        TEXT NOT NULL,              -- e.g. 'fact.value_set'
  payload     TEXT NOT NULL,              -- JSON, readable without a schema
  created_at  TEXT NOT NULL
);
CREATE INDEX _events_outbox ON _events(hlc) WHERE seq IS NULL;

-- LWW clocks: one row per mutable property. A write applies only if its
-- HLC is greater than the stored one.
--   entity: 'deck' | 'fact_type' | 'field' | 'template' | 'fact' | 'card'
--   property: field_id for fact values; otherwise 'name', 'front',
--             'position', 'settings.new_per_day', ...
CREATE TABLE _clocks (
  entity     TEXT NOT NULL,
  entity_id  TEXT NOT NULL,
  property   TEXT NOT NULL,
  hlc        TEXT NOT NULL,
  PRIMARY KEY (entity, entity_id, property)
) WITHOUT ROWID;

-- Client-only sync state. Keys: 'client_id', 'cursor' (last pulled seq),
-- 'hlc' (current clock).
CREATE TABLE _sync (
  key    TEXT PRIMARY KEY,
  value  TEXT NOT NULL
);
